### ISSUE TITLE
Please update offlineimap

### ISSUE THREAD

**Issue by popey** [snapcrafters/offlineimap#1]
There's a new upstream version of offlineimap - 7.1.2 Please update the yaml accordingly. Thanks.

https://github.com/OfflineIMAP/offlineimap/releases

**Comment by Ads20000** [comment]
The yaml is using `master` at the moment...how do we have two yamls - one for stable and one for master? build.snapcraft.io can't build from separate branches at the moment, can it?

**Comment by evandandrea** [comment]
@Ads20000 it cannot. We can use `source-tag:` to point at the new OfflineIMAP release (e4bee74).

**Comment by Ads20000** [comment]
@evandandrea Yeah, [this bug](https://github.com/canonical-websites/build.snapcraft.io/issues/440) is blocking that (which happens to be blocking distributing MuseScore from upstream I think and stuff like that)

**Comment by evandandrea** [comment]
@Ads20000 are you sure? That OfflineIMAP commit is present in the master branch:
https://github.com/OfflineIMAP/offlineimap/commit/e4bee74dad078cf4dc8a8e90b77b2b35e1c09f22

**Comment by Ads20000** [comment]
@evandandrea Oh I meant if we had separate branches for different releases which would've been nice. But yeah that commit is the most recent one in master and I've installed the `edge` snap and it is indeed version 7.1.2 (using `offlineimap --version`). I wouldn't know how to go about testing the snap though, can someone else give it a go please? And then promote that snap to `stable`? :) Presumably new builds would go in `edge` rather than `stable`?

**Comment by popey** [comment]
@evandandrea  Should we not perhaps have an offlineimap-stable and offlineimap-edge with different version number and source tags? I realise this makes the repo a bit messy, and goes against just having one branch, but the alternative is to keep editing and re-editing the yaml, which seems worse to me.

**Comment by Ads20000** [comment]
@popey If we opt to go with that then we should do the same for all the snaps which this is applicable to in the snapcrafters repo. Also note that that will be harder to upstream. Really we need that build service bug fixed.

**Comment by evandandrea** [comment]
I don't think it's unreasonable that we solely target stable versions of OfflineIMAP, reference them in the yaml by their git tag/commit, land in edge, test, and promote to stable.

I don't think it's worth it, but if we wanted to support builds of master as well, you could change the yaml to drop the `source-tag` line between stable versions. Note that you'd need to press the "Build Now" button for every new commit you wanted to build (until daily builds lands).

**Comment by popey** [comment]
This was fixed by https://github.com/snapcrafters/offlineimap/commit/5775d371f3b50f857f2845b141051b3aca9dcb45
