### ISSUE TITLE
offlineimap fails to launch becuase of missing configuration file

### ISSUE THREAD

**Issue by DiogoConstantino** [snapcrafters/offlineimap#4]
`diogo@PRO2:~$ lxc exec mailClienTest -- /bin/bash

root@mailClienTest:\~# snap find OfflineIMAP
Name         Version  Developer     Notes  Summary
offlineimap  v7.2.1   snapcrafters  -      OfflineIMAP
root@mailClienTest:\~# snap install offlineimap
offlineimap v7.2.1 from \'snapcrafters\' installed
root@mailClienTest:\~# offlineimap 
ERROR:root: *** Config file \'/root/snap/offlineimap/120/.offlineimaprc\' does not exist; aborting!

diogo@mailClienTest:\~$ offlineimap 
ERROR:root: *** Config file '/home/diogo/snap/offlineimap/120/.offlineimaprc' does not exist; aborting!`

**Comment by popey** [comment]
This is not a bug. offlineimap requires a configuration file in all packages. Create the file as requested, the documentation has an example. https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf which should be as indicated, in `$HOME/snap/offlineimap/current/.offlineimaprc`
