### ISSUE TITLE
ConfigParser.NoSectionError: No section: 'general'

### ISSUE THREAD

**Issue by varac** [snapcrafters/offlineimap#6]
After removing python2 from my system, I migrated from the ubuntu (19.04) debian package to the offlineimap snap package.
After this, offlineimap fails with:

```
 ~ $ /snap/bin/offlineimap -c /home/varac/.offlineimap/.offlineimaprc
Traceback (most recent call last):
  File "/snap/offlineimap/188/bin/offlineimap", line 22, in <module>
    oi.run()
  File "/snap/offlineimap/188/lib/python2.7/site-packages/offlineimap/init.py", line 89, in run
    options, args = self.__parse_cmd_options()
  File "/snap/offlineimap/188/lib/python2.7/site-packages/offlineimap/init.py", line 265, in __parse_cmd_options
    config.set_if_not_exists('general', 'dry-run', 'False')
  File "/snap/offlineimap/188/lib/python2.7/site-packages/offlineimap/CustomConfig.py", line 135, in set_if_not_exists
    self.set(section, option, value)
  File "/snap/offlineimap/188/usr/lib/python2.7/ConfigParser.py", line 753, in set
    ConfigParser.set(self, section, option, value)
  File "/snap/offlineimap/188/usr/lib/python2.7/ConfigParser.py", line 396, in set
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'general'

 ~ $ head /home/varac/.offlineimap/.offlineimaprc
[general]
accounts   = varac
fsync      = false
…
```

```
 ~ $ snap list offlineimap
Name         Version  Rev  Aufzeichnung  Herausgeber   Hinweise
offlineimap  v7.2.3   188  stable        snapcrafters  -
```

**Comment by varac** [comment]
The (reinstalled) ubuntu debian package (`7.2.2+dfsg1-1`) works fine with the exact same config file:

```
  ~ $ /usr/bin/offlineimap -c ~/.offlineimap/.offlineimaprc
OfflineIMAP 7.2.2
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.57 (system), Python v2.7.16, OpenSSL 1.1.1b  26 Feb 2019
Account sync varac:
 *** Processing account varac
 Establishing connection to imap.***.**:993 (varac@***)
Folder Drafts [acc: varac]:
 Syncing Drafts: IMAP -> Maildir
…
```

**Comment by varac** [comment]
Same issue with OfflineIMAP 7.3.3 installed as snap on ubuntu 20.04

**Comment by varac** [comment]
Issue solved by moving `~/.offlineimap/` to `~/snap/offlineimap/current/` and `~/.offlineimaprc` to `~/snap/offlineimap/current/`.

**Comment by resuser** [comment]
The resolution is a workaround, not a fix.  The user should not expect to have to change the behavior of their scripts depending on what installation method was used.  For example, I have a handful of scripts which use the -c option, and these are broken with the snap installation.
I assume the file access restrictions of the snap will also not allow offlineimap to access the storage areas offlineimap needs to access?  i assume many users will need offlineimap to access local storage and read config files.  it may be best to provide guidance on this in the installation instructions.
