### ISSUE TITLE
7.3.0 fails to build.

### ISSUE THREAD

**Issue by popey** [snapcrafters/offlineimap#7]
I have tried building 7.3.0 as it's just been released. It fails to build in a number of interesting ways. Here's the WIP yaml. http://paste.ubuntu.com/p/X43s45Fv2n/

1) I added rfc6555 as a new requirement (needed by upstream) - fixed
2) the `snap info` line fails because there's a folder called `offlineimap` so it tries to look in there for snap metadata. We need a better way to query the store, or do it in an empty folder, or somehow override snap info looking at the folder - needs fixing
3) It fails building offlineimap with an error in `--single-version-externally-managed` when running set.py.

```
Looking in links: /root/build_offlineimap/parts/offlineimap/python-packages
Collecting offlineimap
Installing collected packages: offlineimap
Successfully installed offlineimap
/root/build_offlineimap/stage/usr/bin/python2 setup.py --no-user-cfg install --single-version-externally-managed --user --record install.txt
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --single-version-externally-managed not recognized
```

**Comment by cjp256** [comment]
Turns out I don't think single-version-externally-managed is really a problem for snapcraft, but this upstream should address it:
https://github.com/cjp256/offlineimap/commit/4668a05ec55a022e35872ba0a5138485e54f127f

**Comment by cjp256** [comment]
Added PR for remaining bits:
https://github.com/snapcrafters/offlineimap/pull/8/files

**Comment by cjp256** [comment]
The single-version-externally-managed error, though displayed, is suppressed by snapcraft for this reason (pip may be able to install it regardless of the setup.py)  -> https://github.com/snapcore/snapcraft/blob/master/snapcraft/plugins/python.py#L389
